{% set name = "czmq" %}
{% set version = "4.3.0-test" %}
{% set sha256 = "8e658939992965ecf77a140d3caf4707f3c8d4a949f3f4ee9fb74a9cd8459bee" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/zeromq/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - libzmq2zeromq.patch
    - missing_stdint_zeromq.patch  # [win and vc<14]

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - cmake
    - autoconf  # [unix]
    - automake  # [unix]
    - libtool  # [unix]
    - pkg-config  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - libuuid  # [unix]
    - pcre
    - zeromq
  run:
    - zeromq

test:
  commands:
    - test -f $PREFIX/lib/libczmq.a  # [unix]
    - test -f $PREFIX/lib/libczmq$SHLIB_EXT  # [unix]
    - test -f $PREFIX/include/czmq.h  # [unix]
    - if not exist %LIBRARY_LIB%\\libczmq.lib exit 1  # [win]
    - if not exist %LIBRARY_INC%\\czmq.h exit 1  # [win]

about:
  home: http://czmq.zeromq.org/
  license: MPL-2.0
  license_file: LICENSE
  summary: 'High-level C binding for 0MQ'

  description: |
    czmq is a high-level C binding for the ZeroMQ <http://zeromq.org/>
    distributed messaging library.
  doc_url: http://czmq.zeromq.org/
  dev_url: https://github.com/zeromq/czmq

extra:
  recipe-maintainers:
    - langmm
