{% set name = "czmq" %}
{% set version = "4.2.1" %}
{% set sha256 = "83457cd32a2c2615b8d7ebcf91b198cb0d8df383a2072b96835ab250164d8a83" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/zeromq/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-cmake-libzmq-to-zeromq.patch
    - 0002-stdint-missing-from-zeromq.patch  # [win and vc<14]
    - 0003-bug-on-macos.patch

build:
  number: 5
  skip: true  # [win and vc<14]

requirements:
  build:
    - cmake
    - ninja  # [win]
    - autoconf  # [unix]
    - automake  # [unix]
    - libtool  # [unix]
    - pkg-config  # [unix]
    - gnuconfig   # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - libuuid  # [unix]
    - pcre
    - zeromq
  run:
    - zeromq

test:
  commands:
    - test -f $PREFIX/lib/libczmq.a  # [unix]
    - test -f $PREFIX/lib/libczmq$SHLIB_EXT  # [unix]
    - test -f $PREFIX/include/czmq.h  # [unix]
    - if not exist %LIBRARY_LIB%\\libczmq.lib exit 1  # [win]
    - if not exist %LIBRARY_INC%\\czmq.h exit 1  # [win]

about:
  home: http://czmq.zeromq.org/
  license: MPL-2.0
  license_file: LICENSE
  summary: High-level C binding for 0MQ

  description: |
    czmq is a high-level C binding for the ZeroMQ <http://zeromq.org/>
    distributed messaging library.
  doc_url: http://czmq.zeromq.org/
  dev_url: https://github.com/zeromq/czmq

extra:
  recipe-maintainers:
    - langmm
