travis:
  secure:
    BINSTAR_TOKEN: qlFkvtU8zFrFeSJMCgzQGcFnjQ6HPGQpO4ZkHwAOeH3trXpJF+dMRO8NdyYmEDIupK5AnsTRPxX34AuMjMK7JiZGunA/pc2E6WQubbo46tn5dafAZeO6+1m60WuLkK0Xsftm6qQBh5OA+gv4zNDJq62E9C/nZM363wbx8P8V+TF+E3YmzJ8FQeB23yUx6CC9ZDkuaJJCkFzkOpZtXHOKOum7f6I/ippsquBjgNT1wuHQiOYw5bN4CIH202d0WK9yBzLLATwL+7wl0IRG+hgsoD+1ieb90b+NIJTKY+XudOTbD7bjbGlQlDPZ6Z6/r5vHEQdcmcCiCjo6bM2lLB7huG8zXPy8znWflK+Yr8VFwC4DOLfP8w8U4pXtGbdGSf1snZ/uZP8v5GSh+jQWhA5fB6but74++KgxGLNbaAe1hop+4LpiB2cJxD8f0glEEYNVKKc3DMo65kVcnaxrN03OVFi/Rojx4owMkRT40ppBlmbfeAfkcucl+W+ctImaNhKrzcwFV+EIlZUz0nOAo2mp4SVQTcDyD1IlNSrRkfgUwaxo0579CJiI2uIIL6aMk/9yHFSqhDWMK0u0of0IibSvcGzH9ePm2QBOiizq1RdNi2nvXp6k5MXOqZnmQooY1Sw3jm2ah3VszfOYMAsNQ4NYgOXSAKTYNFxJ3D1ns69HV14=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
