travis:
  secure:
    BINSTAR_TOKEN: iPrURrKXrnaqn/6DRR+h1OcNUKfofR2oZwQXO0n3dRELtTWZUPXDbLO+T/rsNN8hFcH30O46Uh1NI4kFltJ4WI/dn7bW/HgubxRt9S6SrHZQOYnYQFRcu/7waJiUbJLNPJZweycrTPljMCQ0oOJLyj4VRH143bMKQ2je3A4x13EH44onU5+RoJUxP9kUMdF3D3Lg8RE+O+N0WnXg66ZxOK8FtNge/wsMGCCumOcy5psvpNKZO899TofcYO3F/FxJQOc7lxgHj5zca0agJNuWzdfVgwuHWtVD5ImuhRmlMQN3fk0+8v4HS2o6g69cEwjeQoftLtZarACnjtfD1jEe0ueKrQEbz7fjp5Fe+Oi2YHgAzP4JXWtRvfgDpCraxF5KAs4/KPk5Ov7g+7eMEKzGIMoNIO6HBbxGYTbrvwhi/scxMZ6WlorwrCotgmGlsivHrK2enAMtivE8ORpBb1Ekc1wDwSYDLtLSJjPq6Uxu+mGb2CF1MXghEomdm/SM8O7UTd0OZamawRo2e6MJ0KvoJ8ObHQwKAtiONOcKJPkR1M8pNlz6wUDFxcVKYofV+jTMs6+Ftjy9kLHTRijGQxwv+Kl1x5Azzh4XPlKSXZs+TjBgWwwH9wKZDZPbhioWEx9MWE0fjJpbRAsCSkjmHSncwgtHWI/nUgjk1g9sRMTt/PQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
